module.exports.userServices = require("./authService")
module.exports.newApplicant= require("./newApplicant")
module.exports.classScheduleService = require("./classScheduleService")
module.exports.assessment = require("./assessment")
module.exports.attendanceService = require("./attendanceService")